const products=[
{id:1,n:"Beef Chuck or Brisket",s:"per kg",p:104.99,c:"Meat",e:"🥩"},{id:2,n:"Assorted Chicken Flatties",s:"per kg",p:59.99,c:"Meat",e:"🍗"},{id:3,n:"Your Butcher by SPAR Pork Loin Chops",s:"per kg",p:59.99,c:"Meat",e:"🥩"},{id:4,n:"Ouma Boerewors",s:"per kg",p:109.99,c:"Meat",e:"🌭"},{id:5,n:"Danone Danup Multigrain & Yoghurt Blend",s:"950 g · 2 for R46",p:23,c:"Dairy",e:"🥛"},{id:6,n:"Sea Harvest Oven Crisp Fish Portions",s:"400 g",p:79.99,c:"Frozen",e:"🐟"},{id:7,n:"SPAR Frozen Chicken Gizzards",s:"1 kg",p:42.99,c:"Frozen",e:"🍗"},{id:8,n:"Nestlé Nido 3+ Milk Powder",s:"900 g",p:169.99,c:"Baby",e:"🍼"},{id:9,n:"Huggies Disposable Nappies",s:"Jumbo pack",p:209.99,c:"Baby",e:"👶"},{id:10,n:"Savlon Antiseptic Liquid",s:"750 ml",p:79.99,c:"Personal Care",e:"🧴"},{id:11,n:"Sunlight Dishwashing Liquid",s:"750 ml",p:31.99,c:"Household",e:"🧽"},{id:12,n:"SPAR Briquettes",s:"4 kg",p:79.99,c:"Household",e:"🔥"},{id:13,n:"Kellogg's Corn Flakes",s:"1 kg",p:69.99,c:"Pantry",e:"🥣"},{id:14,n:"SPAR Large Eggs",s:"30s",p:69.99,c:"Dairy",e:"🥚"},{id:15,n:"Red Bull Energy Drink",s:"250 ml · 2 for R44",p:22,c:"Drinks",e:"🥤"},{id:16,n:"White Star Super Maize Meal",s:"10 kg",p:99.99,c:"Pantry",e:"🌽"}];
const stays=[{id:1,n:"Local Guest House",area:"Groblersdal",from:850,e:"🏡"},{id:2,n:"Bush Lodge",area:"Sekhukhune",from:1200,e:"🌿"}];
let cart=JSON.parse(localStorage.getItem("gogo_cart")||"[]"),cat="All";const $=s=>document.querySelector(s);const money=n=>"R"+n.toFixed(2);
function save(){localStorage.setItem("gogo_cart",JSON.stringify(cart))}
function render(){let q=$("#search").value.toLowerCase();let list=products.filter(x=>(cat==="All"||x.c===cat)&&x.n.toLowerCase().includes(q));$("#products").innerHTML=list.map(x=>`<article class="card"><div class="media">${x.img?`<img src="${x.img}" alt="${x.n}">`:`<div class="placeholder">${x.e}</div>`}</div><div class="info"><small>${x.c} · ${x.s}</small><h3>${x.n}</h3><button class="add" aria-label="Add ${x.n}" onclick="add(${x.id})">+</button><div class="price">${money(x.p)}</div></div></article>`).join("")}
function cats(){let cs=["All",...new Set(products.map(x=>x.c))];$("#cats").innerHTML=cs.map(c=>`<button class="${c===cat?"active":""}" onclick="setCat('${c}')">${c}</button>`).join("")}
window.setCat=c=>{cat=c;cats();render()};window.add=id=>{let p=products.find(x=>x.id===id),i=cart.find(x=>x.id===id);i?i.q++:cart.push({...p,q:1});save();basket();$("#drawer").classList.add("open")};window.qty=(id,d)=>{let i=cart.find(x=>x.id===id);if(!i)return;i.q+=d;if(i.q<1)cart=cart.filter(x=>x.id!==id);save();basket()};
function basket(){let sub=cart.reduce((a,x)=>a+x.p*x.q,0),del=sub?35:0;$("#count").textContent=cart.reduce((a,x)=>a+x.q,0);$("#items").innerHTML=cart.length?cart.map(x=>`<div class="cartrow"><span><b>${x.n}</b><br><small>${money(x.p)} each</small></span><div class="qty"><button onclick="qty(${x.id},-1)">−</button><b>${x.q}</b><button onclick="qty(${x.id},1)">+</button></div></div>`).join(""):'<div class="empty">Your basket is empty.</div>';$("#subtotal").textContent=money(sub);$("#delivery").textContent=money(del);$("#total").textContent=money(sub+del)}
function modal(html){$("#modalBody").innerHTML=html;$("#modal").classList.add("open")}
function checkout(){if(!cart.length)return modal("<h2>Your basket is empty</h2><p>Add groceries before checkout.</p>");let sub=cart.reduce((a,x)=>a+x.p*x.q,0),total=sub+35;$("#drawer").classList.remove("open");modal(`<small>SECURE CHECKOUT</small><h2>Delivery details</h2><div class="field"><label>Full name</label><input id="custName" required></div><div class="field"><label>Mobile number</label><input id="custPhone" inputmode="tel" required></div><div class="field"><label>Delivery address</label><input id="custAddress" placeholder="Street / village / landmark" required></div><div class="field"><label>Fulfilment</label><select id="fulfil"><option>Delivery</option><option>Collection</option></select></div><h3>Payment</h3><div class="pay-option"><b>Mobicom Pay</b><br><small>Secure online payment gateway</small></div><div class="notice">Live payment requires the Mobicom Pay server endpoint and production gateway credentials. No secret keys are stored in this website.</div><p><b>Total: ${money(total)}</b></p><button class="primary wide" onclick="placeOrder()">Continue to secure payment</button>`)}
window.placeOrder=async()=>{let n=$("#custName")?.value,p=$("#custPhone")?.value,a=$("#custAddress")?.value,fulfilment=$("#fulfil")?.value||"Delivery";if(!n||!p||!a)return alert("Complete your name, mobile number and address.");let btn=document.querySelector("#modalBody .primary");if(btn){btn.disabled=true;btn.textContent="Preparing payment…"}try{let r=await fetch("/api/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:n,phone:p,address:a,fulfilment,items:cart})});let data=await r.json();if(!r.ok)throw new Error(data.error||"Checkout failed");let orders=JSON.parse(localStorage.getItem("gogo_orders")||"[]");orders.unshift({...data.order,status:"Payment pending"});localStorage.setItem("gogo_orders",JSON.stringify(orders));if(data.payment?.ready&&data.payment.checkoutUrl){let u=new URL(data.payment.checkoutUrl,location.origin);u.searchParams.set("order_id",data.order.id);u.searchParams.set("amount",data.order.total.toFixed(2));u.searchParams.set("currency","ZAR");location.href=u.toString();return}modal(`<h2>Order ${data.order.id}</h2><p>Your order is ready for payment.</p><div class="notice"><b>Mobicom Pay is not live yet.</b> Add the deployed Mobicom Pay checkout URL as the MOBICOM_PAY_URL environment secret.</div><p>Total <b>${money(data.order.total)}</b></p>`)}catch(e){modal(`<h2>Checkout unavailable</h2><p>${e.message}</p><div class="notice">No payment was taken.</div>`)}};
function orders(){let os=JSON.parse(localStorage.getItem("gogo_orders")||"[]");modal("<h2>Your orders</h2>"+(os.length?os.map(o=>`<div class="pay-option"><b>${o.id}</b><br><small>${new Date(o.date).toLocaleString()} · ${o.status}</small><p>${money(o.total)}</p></div>`).join(""):"<p>No orders yet.</p>"))}
function renderStays(){$("#stayGrid").innerHTML=stays.map(s=>`<article class="staycard"><div class="stayimg">${s.e}</div><h3>${s.n}</h3><p>${s.area}</p><b>From ${money(s.from)} / night</b><p><button onclick="stayEnquiry('${s.n}')">View & enquire</button></p></article>`).join("")}
window.stayEnquiry=n=>modal(`<h2>${n}</h2><p>Booking enquiry</p><div class="field"><label>Name</label><input></div><div class="field"><label>Mobile</label><input></div><div class="field"><label>Check-in</label><input type="date"></div><div class="field"><label>Nights</label><input type="number" min="1" value="1"></div><button class="primary wide">Send booking enquiry</button>`);
function switchView(v){document.querySelectorAll(".service").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#groceries").hidden=v!=="groceries";$("#stays").hidden=v!=="stays";scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#search").oninput=render;$("#cartBtn").onclick=()=>$("#drawer").classList.add("open");$("#close").onclick=()=>$("#drawer").classList.remove("open");$("#checkout").onclick=checkout;$("#modalClose").onclick=()=>$("#modal").classList.remove("open");$("#ordersBtn").onclick=orders;$("#bottomOrders").onclick=orders;$("#accountBtn").onclick=()=>modal("<h2>GoGo account</h2><p>Customer profile, saved addresses, favourites and payment preferences will live here.</p>");$("#onboardBtn").onclick=()=>modal('<h2>List your property</h2><p>GoGo merchant onboarding for lodges and guest houses.</p><div class="field"><label>Property name</label><input></div><div class="field"><label>Contact number</label><input></div><div class="field"><label>Location</label><input></div><button class="primary wide">Submit onboarding request</button>');cats();render();basket();renderStays();