const $=s=>document.querySelector(s);let current=null,menu=[],basket=new Map();const fmt=n=>'R'+(n/100).toFixed(2);
function message(id,text){$(id).textContent=text}
async function json(url,options){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
const post=body=>json('/api/restaurants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
$('#registerToggle').onclick=()=>$('#registration').classList.toggle('hidden');
$('#registerForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const d=await post({action:'register',...Object.fromEntries(new FormData(e.target))});message('#registrationStatus','Application #'+d.id+' received. Awaiting approval.');e.target.reset()}catch(err){message('#registrationStatus',err.message)}finally{button.disabled=false}};
async function load(){try{const d=await json('/api/restaurants');const grid=$('#restaurants');grid.replaceChildren();if(!d.restaurants.length){grid.textContent='No approved restaurant partners yet. Restaurants can apply using the button above.';return}for(const r of d.restaurants){const card=document.createElement('article');card.className='restaurant-card';const h=document.createElement('h3');h.textContent=r.name;const p=document.createElement('p');p.className='muted';p.textContent=r.area+' · '+r.cuisine;const b=document.createElement('button');b.textContent='View menu →';b.onclick=()=>openMenu(r.id);card.append(h,p,b);grid.append(card)}}catch(err){message('#restaurants',err.message)}}
async function openMenu(id){try{const d=await json('/api/restaurants?mode=menu&restaurant_id='+encodeURIComponent(id));current=d.restaurant;menu=d.menu;basket.clear();$('#restaurantName').textContent=current.name;$('#restaurantArea').textContent=current.area+' · '+current.cuisine;const list=$('#menu');list.replaceChildren();for(const item of menu){const row=document.createElement('div');row.className='menu-line';const label=document.createElement('div');const name=document.createElement('b');name.textContent=item.name;const desc=document.createElement('p');desc.className='muted';desc.textContent=item.description+' · '+fmt(item.price_cents);label.append(name,desc);const add=document.createElement('button');add.textContent='Add +';add.onclick=()=>{basket.set(item.id,(basket.get(item.id)||0)+1);renderBasket()};row.append(label,add);list.append(row)}if(!menu.length)list.textContent='No menu items available yet.';renderBasket();$('#menuPanel').classList.remove('hidden');$('#menuPanel').scrollIntoView({behavior:'smooth'})}catch(err){alert(err.message)}}
function renderBasket(){const el=$('#basket');el.replaceChildren();let sum=0;for(const [id,qty] of basket){const item=menu.find(m=>m.id===id);if(!item)continue;sum+=qty*item.price_cents;const row=document.createElement('div');row.className='menu-line';const label=document.createElement('span');label.textContent=qty+' × '+item.name+' — '+fmt(qty*item.price_cents);const remove=document.createElement('button');remove.textContent='−';remove.onclick=()=>{if(qty===1)basket.delete(id);else basket.set(id,qty-1);renderBasket()};row.append(label,remove);el.append(row)}const total=document.createElement('p');total.textContent=basket.size?'Estimated total including R35 delivery: '+fmt(sum+3500):'Choose menu items above.';el.append(total)}
$('#back').onclick=()=>{$('#menuPanel').classList.add('hidden');current=null};
$('#orderForm').onsubmit=async e=>{e.preventDefault();if(!current||!basket.size){message('#orderStatus','Add at least one menu item.');return}const button=e.target.querySelector('button');button.disabled=true;try{const d=await post({action:'order',restaurant_id:current.id,items:[...basket].map(([id,qty])=>({id,qty})),...Object.fromEntries(new FormData(e.target))});message('#orderStatus','Request '+d.id+' received. '+d.message);basket.clear();renderBasket();e.target.reset()}catch(err){message('#orderStatus',err.message)}finally{button.disabled=false}};
load();